FROM debian

MAINTAINER vzamyati <vzamyati@student.unit.ua>

RUN apt-get update && apt-get upgrade -y && apt-get install -y build-essential git

# How to build it?
# docker build -t ex01 .

# How to run it?
# docker run --rm -ti ex01