FROM ubuntu

MAINTAINER vzamyati <vzamyati@student.unit.ua>

RUN apt-get update && apt-get upgrade -y && apt-get install -y default-jdk default-jre git vim emacs

# How to build it?
# docker build -t ex04 .

# How to run it?
# docker run --rm -ti ex04